name: .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: InCommodities.sln                     

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Build the project
    - name: Build
      run: dotnet build "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }}

    # Run unit tests
    - name: Test
      run: dotnet test "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --logger "trx;LogFileName=test_results.xml"
      continue-on-error: true

    # Upload test results (optional, but useful for viewing test results in GitHub Actions if tests fail)
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: always() # This ensures the test results are uploaded even if the test step fails
      with:
        name: Test Results
        path: "**/test_results.xml"
